name: buildah-xip

on:
  push:
  schedule:
      - cron: '6 6 6 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  push:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4

    - name: 📗 Outputs
      id: vars
      run: |
        echo "repo_lower=$(echo "${{ github.repository }}" | awk '{print tolower($0)}')" >> $GITHUB_OUTPUT

    - name: 💿 Setup Docker (1/2)
      uses: docker/setup-qemu-action@v3
    - name: 💿 Setup Docker (2/2)
      uses: docker/setup-buildx-action@v3

    - name: 👤 Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 🧪 Test buildah-xip
      if: github.ref != 'refs/heads/master' && github.event_name != 'schedule'
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: false
        cache-from: type=registry,ref=ghcr.io/${{ steps.vars.outputs.repo_lower }}/buildah-xip:cache
        cache-to: type=registry,ref=ghcr.io/${{ steps.vars.outputs.repo_lower }}/buildah-xip:cache,mode=max

    - name: 🚀 Push buildah-xip
      if: github.ref == 'refs/heads/master' || github.event_name == 'schedule'
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          xipdockeruser/buildah-xip:latest
        cache-from: type=registry,ref=ghcr.io/${{ steps.vars.outputs.repo_lower }}/buildah-xip:cache
        cache-to: type=registry,ref=ghcr.io/${{ steps.vars.outputs.repo_lower }}/buildah-xip:cache,mode=max
